# Generated by Django 5.2.3 on 2025-06-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待處理'), ('processing', '處理中'), ('shipped', '已出貨'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20),
        ),
    ]
