# Generated by Django 5.2.3 on 2025-06-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_category_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
