# Generated by Django 5.2.3 on 2025-06-24 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_old_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_category',
        ),
        migrations.AddField(
            model_name='product',
            name='new_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
