# Generated by Django 5.2.3 on 2025-06-24 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_product_old_category_product_new_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_category',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category'),
        ),
    ]
